# Generated by Django 3.0.5 on 2020-04-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog_Breed_Classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='category',
            field=models.IntegerField(choices=[(0, 'OTHERS'), (1, 'sth')], default=0),
        ),
    ]
