# Generated by Django 3.0.5 on 2020-05-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog_Breed_Classifier', '0002_auto_20200430_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='category',
            field=models.CharField(default='Undefined', max_length=50),
        ),
    ]
