# Generated by Django 3.0.5 on 2020-05-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog_Breed_Classifier', '0004_auto_20200501_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='processing_time',
            field=models.CharField(default='0 secondes', max_length=15),
        ),
    ]
